// ...existing code...
// No changes needed here if the logger is already implemented and used by other mods.
// Ensure this file is included in your solution and referenced by ArtifactsPlus.
// ...existing code...